# Generated by Django 3.2.18 on 2023-04-01 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeoLocationType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeoLocationName', models.CharField(max_length=50)),
                ('GeoLocationParentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.geolocations')),
                ('GeoLocationTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.geolocationtype')),
            ],
        ),
    ]
