# Generated by Django 3.2.18 on 2023-04-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocations',
            options={'verbose_name': 'Геолокация', 'verbose_name_plural': 'Геолокации'},
        ),
        migrations.AlterModelOptions(
            name='geolocationtype',
            options={'verbose_name': 'Тип геолокации', 'verbose_name_plural': 'Типы геолокаций'},
        ),
        migrations.AlterField(
            model_name='geolocations',
            name='GeoLocationName',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='geolocations',
            name='GeoLocationParentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.geolocations', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='geolocations',
            name='GeoLocationTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.geolocationtype', verbose_name='Тип геолокации'),
        ),
    ]
