# Generated by Django 3.2.18 on 2023-04-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_freights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freights',
            options={'verbose_name': 'Грузоперевозка', 'verbose_name_plural': 'Грузоперевозки'},
        ),
        migrations.RemoveField(
            model_name='freights',
            name='TLLink',
        ),
        migrations.AddField(
            model_name='freights',
            name='TLLinkMessage',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на пост'),
        ),
        migrations.AddField(
            model_name='freights',
            name='TLLinkUser',
            field=models.CharField(max_length=100, null=True, verbose_name='Ссылка на пользователя'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='Comment',
            field=models.CharField(max_length=500, verbose_name='Инфо'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='Contact',
            field=models.CharField(max_length=100, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='FromLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromloc', to='core.geolocations', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='SubmitedDate',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='ToLoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toloc', to='core.geolocations', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='freights',
            name='Weight',
            field=models.CharField(max_length=50, verbose_name='Вес'),
        ),
    ]
