# Generated by Django 4.2 on 2023-05-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_freights_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationSynonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=20)),
                ('geoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.geolocations')),
            ],
        ),
    ]
