# Generated by Django 4.2 on 2023-05-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_geolocationsynonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocations',
            name='FromGeoLocationWord',
            field=models.CharField(default='', max_length=50, verbose_name='Из ...'),
        ),
        migrations.AddField(
            model_name='geolocations',
            name='ToGeoLocationWord',
            field=models.CharField(default='', max_length=50, verbose_name='В ...'),
        ),
    ]
